### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by Xuan2023** [annacode747/novel-naifu-aki-cpu#2]
(base) C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main>python main.py
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from hydra_node.config import init_config_model
  File "C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main\hydra_node\config.py", line 10, in <module>
    from hydra_node.models import StableDiffusionModel, DalleMiniModel, BasedformerModel, EmbedderModel
  File "C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main\hydra_node\models.py", line 13, in <module>
    from torchvision.utils import make_grid
  File "C:\Users\18910\Anaconda3\lib\site-packages\torchvision\__init__.py", line 5, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "C:\Users\18910\Anaconda3\lib\site-packages\torchvision\models\__init__.py", line 16, in <module>
    from .maxvit import *
  File "C:\Users\18910\Anaconda3\lib\site-packages\torchvision\models\maxvit.py", line 3, in <module>
    from typing import Any, Callable, List, Optional, OrderedDict, Sequence, Tuple
ImportError: cannot import name 'OrderedDict' from 'typing' (C:\Users\18910\Anaconda3\lib\typing.py)

**Comment by Xuan2023** [comment]
所有模块已经安装，模型也放入了

**Comment by annacode747** [comment]
https://pan.baidu.com/s/1HfySrVnFmeS1AkhFnBbhpA?pwd=9976 这里 有模型

**Comment by Xuan2023** [comment]
> https://pan.baidu.com/s/1HfySrVnFmeS1AkhFnBbhpA?pwd=9976 这里 有模型

下载后放入就好？

**Comment by Xuan2023** [comment]
> 

放入了这个模型
(base) C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main>python main.py
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from hydra_node.config import init_config_model
  File "C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main\hydra_node\config.py", line 10, in <module>
    from hydra_node.models import StableDiffusionModel, DalleMiniModel, BasedformerModel, EmbedderModel
  File "C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main\hydra_node\models.py", line 13, in <module>
    from torchvision.utils import make_grid
  File "C:\Users\18910\Anaconda3\lib\site-packages\torchvision\__init__.py", line 5, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "C:\Users\18910\Anaconda3\lib\site-packages\torchvision\models\__init__.py", line 16, in <module>
    from .maxvit import *
  File "C:\Users\18910\Anaconda3\lib\site-packages\torchvision\models\maxvit.py", line 3, in <module>
    from typing import Any, Callable, List, Optional, OrderedDict, Sequence, Tuple
ImportError: cannot import name 'OrderedDict' from 'typing' (C:\Users\18910\Anaconda3\lib\typing.py)

**Comment by Xuan2023** [comment]
> https://pan.baidu.com/s/1HfySrVnFmeS1AkhFnBbhpA?pwd=9976 这里 有模型

放入了这个模型
(base) C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main>python main.py
Traceback (most recent call last):
File "main.py", line 11, in
from hydra_node.config import init_config_model
File "C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main\hydra_node\config.py", line 10, in
from hydra_node.models import StableDiffusionModel, DalleMiniModel, BasedformerModel, EmbedderModel
File "C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main\hydra_node\models.py", line 13, in
from torchvision.utils import make_grid
File "C:\Users\18910\Anaconda3\lib\site-packages\torchvision_init_.py", line 5, in
from torchvision import datasets, io, models, ops, transforms, utils
File "C:\Users\18910\Anaconda3\lib\site-packages\torchvision\models_init_.py", line 16, in
from .maxvit import *
File "C:\Users\18910\Anaconda3\lib\site-packages\torchvision\models\maxvit.py", line 3, in
from typing import Any, Callable, List, Optional, OrderedDict, Sequence, Tuple
ImportError: cannot import name 'OrderedDict' from 'typing' (C:\Users\18910\Anaconda3\lib\typing.py)

**Comment by Xuan2023** [comment]
> https://pan.baidu.com/s/1HfySrVnFmeS1AkhFnBbhpA?pwd=9976 这里 有模型

(base) C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main>python main.py
lowvram: True
using dtype: float32
Starting Hydra Node HTTP TOKEN=None
2022-11-10 17:23:22,322 INFO config.py(10852) - CPU: AMD64 Family 21 Model 19 Stepping 1, AuthenticAMD
2022-11-10 17:23:22,322 INFO config.py(10852) - MODEL: stable-diffusion
2022-11-10 17:23:22,322 INFO models.py(10852) - Loading model from folder models/animefull-final-pruned
Loading model from models\animefull-final-pruned\model.ckpt
Traceback (most recent call last):
  File "C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main\hydra_node\config.py", line 186, in init_config_model
    model = no_init(lambda: model_map[config.model_name](config))
  File "C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main\hydra_node\config.py", line 36, in no_init
    result = loading_code()
  File "C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main\hydra_node\config.py", line 186, in <lambda>
    model = no_init(lambda: model_map[config.model_name](config))
  File "C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main\hydra_node\models.py", line 219, in __init__
    model, model_config = self.from_folder(config.model_path)
  File "C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main\hydra_node\models.py", line 321, in from_folder
    model = self.load_model_from_config(model_config, model_path)
  File "C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main\hydra_node\models.py", line 341, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main\ldm\util.py", line 87, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "C:\Users\18910\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\18910\Downloads\novel-naifu-aki-cpu-main\novel-naifu-aki-cpu-main\ldm\models\diffusion\ddpm.py", line 12, in <module>
    import pytorch_lightning as pl
ModuleNotFoundError: No module named 'pytorch_lightning'
2022-11-10 17:23:30,148 ERROR config.py(10852) - Failed to load model: No module named 'pytorch_lightning'
